# Environment
ENVIRONMENT = "production"

# Supabase Database
SUPABASE_URL = "https://mgdgovkyomfkcljutcsj.supabase.co"
SUPABASE_KEY = "YOUR_SUPABASE_ANON_KEY_HERE"
SUPABASE_SERVICE_KEY = "YOUR_SUPABASE_SERVICE_KEY_HERE"

# Stripe Payment (USE LIVE KEYS FOR PRODUCTION)
STRIPE_PUBLISHABLE_KEY = "pk_live_YOUR_LIVE_KEY_HERE"
STRIPE_SECRET_KEY = "sk_live_YOUR_LIVE_KEY_HERE"
STRIPE_WEBHOOK_SECRET = "whsec_YOUR_WEBHOOK_SECRET_HERE"

# OpenRouter AI
OPENROUTER_API_KEY = "YOUR_OPENROUTER_KEY_HERE"

# Admin Credentials
ADMIN_EMAIL = "admin@wantamock.com"
ADMIN_PASSWORD = "YOUR_SECURE_PASSWORD_HERE"
